import React,{useEffect,useState}from'react';import{View,Text,TextInput,Pressable,FlatList,StyleSheet,Alert,Linking}from'react-native';import*as Location from'expo-location';
const API=process.env.EXPO_PUBLIC_API_URL||'https://api.elitekurye.com';const C={bg:'#090a0d',panel:'#15181e',red:'#e51d2a',muted:'#9aa2ad',white:'#fff',green:'#23c77a'};
export default function App(){const[phone,setPhone]=useState(''),[pass,setPass]=useState(''),[token,setToken]=useState(null),[jobs,setJobs]=useState([]),[busy,setBusy]=useState(false);
const api=async(p,o={})=>{o.headers={'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})};let r=await fetch(API+p,o),j=await r.json();if(!r.ok)throw Error(j.error||'Hata');return j};
const load=async()=>{try{setJobs(await api('/orders'))}catch(e){}};const gps=async()=>{try{let p=await Location.requestForegroundPermissionsAsync();if(p.status!=='granted')return;let l=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});await api('/couriers/location',{method:'POST',body:JSON.stringify({latitude:l.coords.latitude,longitude:l.coords.longitude,accuracy:l.coords.accuracy})})}catch(e){}};
useEffect(()=>{if(token){load();gps();let t=setInterval(()=>{load();gps()},30000);return()=>clearInterval(t)}},[token]);
async function login(){setBusy(true);try{let j=await api('/auth/login',{method:'POST',body:JSON.stringify({phone,password:pass})});setToken(j.token)}catch(e){Alert.alert('Giriş',e.message)}finally{setBusy(false)}}
async function status(id,s){try{await api('/orders/'+id+'/status',{method:'POST',body:JSON.stringify({status:s})});load()}catch(e){Alert.alert('Durum',e.message)}}
if(!token)return <View style={S.screen}><Text style={S.logo}>ELİTE <Text style={{color:C.red}}>KURYE</Text></Text><Text style={S.sub}>Kurye Uygulaması</Text><TextInput style={S.input} placeholder="Telefon" placeholderTextColor="#777" value={phone} onChangeText={setPhone}/><TextInput style={S.input} placeholder="Şifre" placeholderTextColor="#777" secureTextEntry value={pass} onChangeText={setPass}/><Pressable style={S.btn} onPress={login}><Text style={S.bt}>Giriş Yap</Text></Pressable></View>;
return <View style={S.screen}><View style={S.header}><Text style={S.logo}>İŞLERİM</Text><Text style={{color:C.green}}>● GPS aktif</Text></View><FlatList data={jobs} keyExtractor={x=>x.id} ListEmptyComponent={<Text style={S.sub}>Şu an atanmış iş yok.</Text>} renderItem={({item})=><View style={S.card}><Text style={S.h}>#{item.id.slice(0,8)} • {item.restaurant_name}</Text><Text style={S.txt}>{item.customer_name}</Text><Text style={S.sub}>{item.delivery_address}</Text><Text style={S.txt}>{item.package_count} paket • {Number(item.courier_cost_kurus)/100} TL</Text><View style={{height:8}}/>{item.status==='ASSIGNED'&&<Pressable style={S.btn} onPress={()=>status(item.id,'PICKED_UP')}><Text style={S.bt}>PAKETİ ALDIM</Text></Pressable>}{item.status==='PICKED_UP'&&<Pressable style={S.btn} onPress={()=>{status(item.id,'OUT_FOR_DELIVERY');Linking.openURL('https://maps.google.com/?q='+encodeURIComponent(item.delivery_address))}}><Text style={S.bt}>YOLA ÇIKTIM / NAVİGASYON</Text></Pressable>}{item.status==='OUT_FOR_DELIVERY'&&<Pressable style={S.btn} onPress={()=>status(item.id,'DELIVERED')}><Text style={S.bt}>TESLİM ETTİM</Text></Pressable>}</View>}/></View>}
const S=StyleSheet.create({screen:{flex:1,backgroundColor:C.bg,padding:20,paddingTop:65},logo:{fontSize:28,fontWeight:'900',color:C.white},sub:{color:C.muted,marginTop:6,marginBottom:14},input:{backgroundColor:'#fff',borderRadius:9,padding:14,marginTop:10},btn:{backgroundColor:C.red,padding:13,borderRadius:9,alignItems:'center'},bt:{color:'#fff',fontWeight:'800'},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:18},card:{backgroundColor:C.panel,borderRadius:13,padding:16,marginBottom:12},h:{color:C.white,fontWeight:'800',fontSize:16},txt:{color:C.white,marginTop:7}});