require('dotenv').config();
const express=require('express'),helmet=require('helmet'),cors=require('cors'),rateLimit=require('express-rate-limit');
const {Pool}=require('pg'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),http=require('http'),{WebSocketServer}=require('ws');
const app=express(), server=http.createServer(app), wss=new WebSocketServer({server});
const pool=new Pool({connectionString:process.env.DATABASE_URL}), SECRET=process.env.JWT_SECRET;
app.use(helmet()); app.use(cors({origin:process.env.WEB_ORIGIN||false})); app.use(express.json({limit:'2mb'}));
app.use(rateLimit({windowMs:60000,max:300}));
const q=(s,a=[])=>pool.query(s,a);
const broadcast=(type,data)=>{const msg=JSON.stringify({type,data});wss.clients.forEach(c=>{if(c.readyState===1)c.send(msg)})};
wss.on('connection',ws=>ws.send(JSON.stringify({type:'connected'})));
function auth(roles=[]){return async(req,res,next)=>{try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'Giriş gerekli'});req.user=jwt.verify(h.slice(7),SECRET);if(roles.length&&!roles.includes(req.user.role))return res.status(403).json({error:'Yetkisiz'});next()}catch(e){res.status(401).json({error:'Geçersiz oturum'})}}}
app.get('/health',(req,res)=>res.json({ok:true,service:'elite-kurye-api',version:'2.0'}));
app.post('/auth/login',async(req,res)=>{try{const {phone,password}=req.body;const r=await q('SELECT id,role,full_name,password_hash FROM users WHERE phone=$1 AND is_active=true',[phone]);if(!r.rowCount||!await bcrypt.compare(password,r.rows[0].password_hash))return res.status(401).json({error:'Telefon veya şifre hatalı'});const u=r.rows[0],token=jwt.sign({id:u.id,role:u.role,name:u.full_name},SECRET,{expiresIn:'7d'});res.json({token,user:{id:u.id,role:u.role,name:u.full_name}})}catch(e){res.status(500).json({error:e.message})}});
app.get('/dashboard',auth(['ADMIN']),async(req,res)=>{const r=await q(`SELECT COUNT(*)::int orders,COUNT(*) FILTER(WHERE status='WAITING')::int waiting,COUNT(*) FILTER(WHERE status IN ('ASSIGNED','PICKED_UP','OUT_FOR_DELIVERY'))::int active,COUNT(*) FILTER(WHERE status='DELIVERED')::int delivered,COALESCE(SUM(restaurant_fee_kurus),0)::bigint revenue,COALESCE(SUM(courier_cost_kurus),0)::bigint courier_cost,COALESCE(SUM(gross_margin_kurus),0)::bigint gross FROM orders`);res.json(r.rows[0])});
app.get('/orders',auth(['ADMIN','RESTAURANT','COURIER']),async(req,res)=>{let sql=`SELECT o.*,r.name restaurant_name,u.full_name courier_name FROM orders o JOIN restaurants r ON r.id=o.restaurant_id LEFT JOIN couriers c ON c.id=o.courier_id LEFT JOIN users u ON u.id=c.user_id`,a=[];if(req.user.role==='RESTAURANT'){const x=await q('SELECT id FROM restaurants WHERE user_id=$1',[req.user.id]);if(!x.rowCount)return res.json([]);a=[x.rows[0].id];sql+=' WHERE o.restaurant_id=$1'}if(req.user.role==='COURIER'){const x=await q('SELECT id FROM couriers WHERE user_id=$1',[req.user.id]);if(!x.rowCount)return res.json([]);a=[x.rows[0].id];sql+=' WHERE o.courier_id=$1'}sql+=' ORDER BY o.created_at DESC';res.json((await q(sql,a)).rows)});
app.get('/couriers',auth(['ADMIN']),async(req,res)=>res.json((await q(`SELECT c.*,u.full_name,u.phone FROM couriers c JOIN users u ON u.id=c.user_id ORDER BY u.full_name`)).rows));
app.get('/restaurants',auth(['ADMIN','RESTAURANT']),async(req,res)=>res.json((await q(`SELECT r.* FROM restaurants r ${req.user.role==='RESTAURANT'?'WHERE r.user_id=$1':''} ORDER BY r.name`,req.user.role==='RESTAURANT'?[req.user.id]:[])).rows));
app.post('/orders',auth(['ADMIN','RESTAURANT']),async(req,res)=>{const {restaurantId,customerName,customerPhone,deliveryAddress,latitude,longitude,distanceKm,packageCount}=req.body;const c=await pool.connect();try{await c.query('BEGIN');let rid=restaurantId;if(req.user.role==='RESTAURANT'){const x=await c.query('SELECT id FROM restaurants WHERE user_id=$1',[req.user.id]);if(!x.rowCount)throw Error('Restoran hesabı bulunamadı');rid=x.rows[0].id}const rule=await c.query(`SELECT price_kurus FROM pricing_rules WHERE restaurant_id=$1 AND min_km <= $2 AND (max_km IS NULL OR $2 < max_km) ORDER BY min_km DESC LIMIT 1`,[rid,distanceKm]);if(!rule.rowCount)throw Error('Mesafe tarifesi yok');const fee=Number(rule.rows[0].price_kurus)*Number(packageCount);const o=await c.query(`INSERT INTO orders(restaurant_id,customer_name,customer_phone,delivery_address,latitude,longitude,distance_km,package_count,restaurant_fee_kurus) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[rid,customerName,customerPhone||null,deliveryAddress,latitude||null,longitude||null,distanceKm,packageCount,fee]);await c.query('INSERT INTO order_events(order_id,status,actor_user_id) VALUES($1,$2,$3)',[o.rows[0].id,'WAITING',req.user.id]);await c.query('COMMIT');broadcast('order.created',o.rows[0]);res.status(201).json(o.rows[0])}catch(e){await c.query('ROLLBACK');res.status(400).json({error:e.message})}finally{c.release()}});
app.post('/orders/:id/assign',auth(['ADMIN']),async(req,res)=>{const c=await pool.connect();try{await c.query('BEGIN');const o=(await c.query('SELECT * FROM orders WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];const cr=(await c.query('SELECT * FROM couriers WHERE id=$1',[req.body.courierId])).rows[0];if(!o||!cr)throw Error('Sipariş/kurye bulunamadı');const cost=Number(cr.rate_kurus)*o.package_count,gross=Number(o.restaurant_fee_kurus)-cost;const u=await c.query(`UPDATE orders SET courier_id=$1,status='ASSIGNED',courier_cost_kurus=$2,gross_margin_kurus=$3 WHERE id=$4 RETURNING *`,[cr.id,cost,gross,o.id]);await c.query('INSERT INTO order_events(order_id,status,actor_user_id,note) VALUES($1,$2,$3,$4)',[o.id,'ASSIGNED',req.user.id,'Kurye atandı']);await c.query('COMMIT');broadcast('order.assigned',u.rows[0]);res.json(u.rows[0])}catch(e){await c.query('ROLLBACK');res.status(400).json({error:e.message})}finally{c.release()}});
app.post('/orders/:id/status',auth(['ADMIN','COURIER']),async(req,res)=>{const allowed=['PICKED_UP','OUT_FOR_DELIVERY','DELIVERED','CANCELLED'];if(!allowed.includes(req.body.status))return res.status(400).json({error:'Geçersiz durum'});const c=await pool.connect();try{await c.query('BEGIN');const o=(await c.query('SELECT * FROM orders WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!o)throw Error('Sipariş bulunamadı');if(req.user.role==='COURIER'){const cr=(await c.query('SELECT id FROM couriers WHERE user_id=$1',[req.user.id])).rows[0];if(!cr||cr.id!==o.courier_id)throw Error('Sipariş size ait değil')}const u=await c.query(`UPDATE orders SET status=$1,delivered_at=CASE WHEN $2 THEN now() ELSE delivered_at END WHERE id=$3 RETURNING *`,[req.body.status,req.body.status==='DELIVERED',o.id]);await c.query('INSERT INTO order_events(order_id,status,actor_user_id) VALUES($1,$2,$3)',[o.id,req.body.status,req.user.id]);if(req.body.status==='DELIVERED'){await c.query('INSERT INTO financial_ledger(order_id,restaurant_id,entry_type,amount_kurus) VALUES($1,$2,$3,$4)',[o.id,o.restaurant_id,'RESTAURANT_CHARGE',o.restaurant_fee_kurus]);await c.query('INSERT INTO financial_ledger(order_id,courier_id,entry_type,amount_kurus) VALUES($1,$2,$3,$4)',[o.id,o.courier_id,'COURIER_EARNING',o.courier_cost_kurus])}await c.query('COMMIT');broadcast('order.status',u.rows[0]);res.json(u.rows[0])}catch(e){await c.query('ROLLBACK');res.status(400).json({error:e.message})}finally{c.release()}});
app.post('/couriers/location',auth(['COURIER']),async(req,res)=>{const cr=await q('SELECT id FROM couriers WHERE user_id=$1',[req.user.id]);if(!cr.rowCount)return res.status(404).json({error:'Kurye yok'});await q('UPDATE couriers SET latitude=$1,longitude=$2,last_location_at=now() WHERE id=$3',[req.body.latitude,req.body.longitude,cr.rows[0].id]);await q('INSERT INTO courier_location_history(courier_id,latitude,longitude,accuracy) VALUES($1,$2,$3,$4)',[cr.rows[0].id,req.body.latitude,req.body.longitude,req.body.accuracy||null]);broadcast('courier.location',{courierId:cr.rows[0].id,latitude:req.body.latitude,longitude:req.body.longitude});res.json({ok:true})});

app.get('/reports/summary',auth(['ADMIN']),async(req,res)=>{const r=await q(`SELECT date_trunc('day',created_at)::date day,COUNT(*)::int orders,COALESCE(SUM(restaurant_fee_kurus),0)::bigint revenue,COALESCE(SUM(courier_cost_kurus),0)::bigint courier_cost,COALESCE(SUM(gross_margin_kurus),0)::bigint gross FROM orders WHERE created_at >= now()-interval '31 days' GROUP BY 1 ORDER BY 1 DESC`);res.json(r.rows)});
app.get('/pricing/:restaurantId',auth(['ADMIN','RESTAURANT']),async(req,res)=>{let x=await q('SELECT id FROM restaurants WHERE id=$1 AND ($2=true OR user_id=$3)',[req.params.restaurantId,req.user.role==='ADMIN',req.user.id]);if(!x.rowCount)return res.status(403).json({error:'Yetkisiz'});res.json((await q('SELECT * FROM pricing_rules WHERE restaurant_id=$1 ORDER BY min_km',[req.params.restaurantId])).rows)});
app.post('/pricing/:restaurantId',auth(['ADMIN','RESTAURANT']),async(req,res)=>{const {minKm,maxKm,priceKurus}=req.body;let x=await q('SELECT id FROM restaurants WHERE id=$1 AND ($2=true OR user_id=$3)',[req.params.restaurantId,req.user.role==='ADMIN',req.user.id]);if(!x.rowCount)return res.status(403).json({error:'Yetkisiz'});const r=await q('INSERT INTO pricing_rules(restaurant_id,min_km,max_km,price_kurus) VALUES($1,$2,$3,$4) RETURNING *',[req.params.restaurantId,minKm,maxKm||null,priceKurus]);await q('INSERT INTO restaurant_price_audit(restaurant_id,min_km,max_km,price_kurus,changed_by) VALUES($1,$2,$3,$4,$5)',[req.params.restaurantId,minKm,maxKm||null,priceKurus,req.user.id]);res.status(201).json(r.rows[0])});
app.post('/push/register',auth(),async(req,res)=>{await q('INSERT INTO push_tokens(user_id,token,platform) VALUES($1,$2,$3) ON CONFLICT(token) DO UPDATE SET user_id=$1,platform=$3',[req.user.id,req.body.token,req.body.platform||'unknown']);res.json({ok:true})});
app.get('/notifications',auth(),async(req,res)=>res.json((await q('SELECT * FROM notifications WHERE user_id=$1 ORDER BY created_at DESC LIMIT 100',[req.user.id])).rows));
app.post('/orders/:id/proof',auth(['ADMIN','COURIER']),async(req,res)=>{const o=(await q('SELECT * FROM orders WHERE id=$1',[req.params.id])).rows[0];if(!o)return res.status(404).json({error:'Sipariş yok'});if(req.user.role==='COURIER'){const c=(await q('SELECT id FROM couriers WHERE user_id=$1',[req.user.id])).rows[0];if(!c||c.id!==o.courier_id)return res.status(403).json({error:'Yetkisiz'})}const r=await q(`INSERT INTO delivery_proofs(order_id,delivery_code,photo_path,customer_signature,notes) VALUES($1,$2,$3,$4,$5) ON CONFLICT(order_id) DO UPDATE SET delivery_code=EXCLUDED.delivery_code,photo_path=EXCLUDED.photo_path,customer_signature=EXCLUDED.customer_signature,notes=EXCLUDED.notes RETURNING *`,[o.id,req.body.deliveryCode||null,req.body.photoPath||null,req.body.customerSignature||null,req.body.notes||null]);res.json(r.rows[0])});
app.get('/couriers/live',auth(['ADMIN']),async(req,res)=>res.json((await q(`SELECT c.id,u.full_name,c.latitude,c.longitude,c.last_location_at,c.is_available,c.motor_type FROM couriers c JOIN users u ON u.id=c.user_id WHERE c.latitude IS NOT NULL`)).rows));


app.post('/users',auth(['ADMIN']),async(req,res)=>{try{const {role,fullName,phone,password,motorType,rateKurus}=req.body;if(!['ADMIN','RESTAURANT','COURIER'].includes(role))throw Error('Geçersiz rol');const hash=await bcrypt.hash(password,12);const u=await q('INSERT INTO users(role,full_name,phone,password_hash) VALUES($1,$2,$3,$4) RETURNING id,role,full_name,phone',[role,fullName,phone,hash]);if(role==='COURIER')await q('INSERT INTO couriers(user_id,motor_type,rate_kurus) VALUES($1,$2,$3)',[u.rows[0].id,motorType||'OWN',rateKurus||6500]);if(role==='RESTAURANT')await q('INSERT INTO restaurants(user_id,name) VALUES($1,$2)',[u.rows[0].id,fullName]);await q('INSERT INTO audit_logs(user_id,action,entity_type,entity_id) VALUES($1,$2,$3,$4)',[req.user.id,'CREATE_USER','USER',u.rows[0].id]);res.status(201).json(u.rows[0])}catch(e){res.status(400).json({error:e.message})}});
app.patch('/couriers/:id',auth(['ADMIN']),async(req,res)=>{const {rateKurus,isAvailable,motorType}=req.body;const r=await q(`UPDATE couriers SET rate_kurus=COALESCE($1,rate_kurus),is_available=COALESCE($2,is_available),motor_type=COALESCE($3,motor_type) WHERE id=$4 RETURNING *`,[rateKurus,isAvailable,motorType,req.params.id]);res.json(r.rows[0]||{})});
app.get('/finance/summary',auth(['ADMIN']),async(req,res)=>{const r=await q(`SELECT COALESCE(SUM(CASE WHEN entry_type='RESTAURANT_CHARGE' THEN amount_kurus ELSE 0 END),0)::bigint revenue,COALESCE(SUM(CASE WHEN entry_type='COURIER_EARNING' THEN amount_kurus ELSE 0 END),0)::bigint courier,COALESCE(SUM(CASE WHEN entry_type='RESTAURANT_CHARGE' THEN amount_kurus ELSE -amount_kurus END),0)::bigint gross FROM financial_ledger`);const e=await q(`SELECT COALESCE(SUM(amount_kurus),0)::bigint expenses FROM expenses`);res.json({...r.rows[0],expenses:e.rows[0].expenses,net:Number(r.rows[0].gross)-Number(e.rows[0].expenses)})});
app.post('/expenses',auth(['ADMIN']),async(req,res)=>{const r=await q('INSERT INTO expenses(description,amount_kurus,category,expense_date,created_by) VALUES($1,$2,$3,$4,$5) RETURNING *',[req.body.description,req.body.amountKurus,req.body.category,req.body.expenseDate||null,req.user.id]);res.status(201).json(r.rows[0])});
app.get('/expenses',auth(['ADMIN']),async(req,res)=>res.json((await q('SELECT * FROM expenses ORDER BY expense_date DESC,created_at DESC')).rows));
app.get('/courier-payouts',auth(['ADMIN']),async(req,res)=>res.json((await q(`SELECT p.*,u.full_name FROM courier_payouts p JOIN couriers c ON c.id=p.courier_id JOIN users u ON u.id=c.user_id ORDER BY p.created_at DESC`)).rows));
app.post('/courier-payouts/generate',auth(['ADMIN']),async(req,res)=>{const start=req.body.startDate,end=req.body.endDate;const rows=(await q(`SELECT c.id,SUM(o.courier_cost_kurus)::bigint total,COUNT(*)::int cnt FROM orders o JOIN couriers c ON c.id=o.courier_id WHERE o.status='DELIVERED' AND o.delivered_at::date BETWEEN $1 AND $2 GROUP BY c.id`,[start,end])).rows;for(const x of rows)await q(`INSERT INTO courier_payouts(courier_id,period_start,period_end,total_orders,total_kurus) VALUES($1,$2,$3,$4,$5)`,[x.id,start,end,x.cnt,x.total]);res.json({created:rows.length})});
app.get('/restaurant-invoices',auth(['ADMIN','RESTAURANT']),async(req,res)=>{let sql=`SELECT i.*,r.name FROM restaurant_invoices i JOIN restaurants r ON r.id=i.restaurant_id`,a=[];if(req.user.role==='RESTAURANT'){sql+=' WHERE r.user_id=$1';a=[req.user.id]}res.json((await q(sql,a)).rows)});
app.post('/restaurant-invoices/generate',auth(['ADMIN']),async(req,res)=>{const start=req.body.startDate,end=req.body.endDate;const rows=(await q(`SELECT restaurant_id,SUM(restaurant_fee_kurus)::bigint total,COUNT(*)::int cnt FROM orders WHERE status='DELIVERED' AND delivered_at::date BETWEEN $1 AND $2 GROUP BY restaurant_id`,[start,end])).rows;for(const x of rows)await q(`INSERT INTO restaurant_invoices(restaurant_id,period_start,period_end,total_orders,total_kurus) VALUES($1,$2,$3,$4,$5)`,[x.restaurant_id,start,end,x.cnt,x.total]);res.json({created:rows.length})});
app.post('/audit',auth(),async(req,res)=>{await q('INSERT INTO audit_logs(user_id,action,entity_type,entity_id,details) VALUES($1,$2,$3,$4,$5)',[req.user.id,req.body.action,req.body.entityType||null,req.body.entityId||null,req.body.details||{}]);res.json({ok:true})});

server.listen(process.env.PORT||3000,'0.0.0.0',()=>console.log('ELİTE KURYE API v2 hazır'));
